/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./cloudflare-env.d.ts` (hash: e989bea68ec83c414ae5b6fbfaef9e6d)
interface __BaseEnv_CloudflareEnv {
	BUCKET: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	INBOUND_QUEUE: Queue;
	OUTBOUND_QUEUE: Queue;
	LOGIN_RATE_LIMIT: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	D1_DATABASE_ID: "a9443977-88d2-46c1-bdc4-052784b445e8";
	NEXTJS_ENV: string;
	CF_AID: string;
	CF_EMAIL_WORKER_NAME: string;
	CF_TOKEN: string;
	REALTIME: DurableObjectNamespace<import("./worker").RealtimeHub>;
	WORKER_SELF_REFERENCE: Service<typeof import("./worker").default>;
	DATABASE_BACKUP_WORKFLOW: Workflow<Parameters<import("./worker").DatabaseBackupWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "RealtimeHub";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "D1_DATABASE_ID" | "NEXTJS_ENV" | "CF_AID" | "CF_EMAIL_WORKER_NAME" | "CF_TOKEN">> {}
}
